const centralPark ={
    roomId: '60-amer',
    rooms: [
        {
            id:'60-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'61-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'62-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'63-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'64-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'65-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'66-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'67-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'68-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'69-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'70-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'71-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'72-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'73-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'74-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'75-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'76-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'77-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'78-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'79-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'80-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'81-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'82-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'83-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'84-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'85-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'86-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'87-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'88-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'89-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'90-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'91-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'92-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'93-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'94-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'95-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'96-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'97-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'98-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'99-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'100-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'101-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'102-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'103-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'104-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'105-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'106-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'107-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'108-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['west'],id:''},
                {dir:['South'],id:''},
            ]
        },
        {
            id:'109-amer',
            name:'',
            desc:``,
            exits:[
                {dir:['South'],id:''},
                {dir:['west'],id:''}
            ]
        },
        //7th Avenue
        {
            id:'60-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['south'],id:''}
            ]
        },
        {
            id:'61-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'62-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'63-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'64-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'65-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'66-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'67-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'66-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'67-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'68-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'69-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'70-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'71-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'72-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'73-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'74-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'75-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'76-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'77-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'78-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'79-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'80-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'81-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'82-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'83-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'edga-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'85-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'86-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'87-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'88-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'89-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'90-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'91-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'92-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'93-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'94-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'95-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'96-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'97-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'98-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'99-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'100-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'101-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'102-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'103-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'104-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'105-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'106-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'107-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'108-7',
            name:'',
            desc:``,
            exits:[
                {dir:['north'],id:''},
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },
        {
            id:'109-7',
            name:'',
            desc:``,
            exits:[
                {dir:['east'],id:''},
                {dir:['South'],id:''}
            ]
        },



    ]








}